name: Deploy to ECS

on:
  push:
    branches: [main]
    paths:
      - 'terraform/**'
      - 'app/**'
      - '.github/workflows/**'

jobs:
  # terraform apply/destroy
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.6.6
        terraform_wrapper: false

    - name: Initialize Terraform
      run: terraform init

    - name: Terraform Plan
      run: terraform plan

    - name: Execute Terraform Apply
      run: |
        terraform apply -auto-approve
    
    - name: Handle output
      id: export 
      run: |
        outputs=$(terraform output -json)
        vpc_id_tmp=$(echo "$outputs" | jq -c .infrastructure_output.value.vpc_id)
        echo "vpc_id=$vpc_id_tmp" >> $GITHUB_OUTPUT
        ecs_repo_name_tmp=$(echo "$outputs" | jq -c .infrastructure_output.value.ecs_repo_name)
        echo "ecs_repo_name=$ecs_repo_name_tmp" >> $GITHUB_OUTPUT
        aws_account_id_tmp=$(echo "$outputs" | jq -c .infrastructure_output.value.aws_account_id)
        echo "aws_account_id=$aws_account_id_tmp" >> $GITHUB_OUTPUT
    
    outputs:
        vpc_id: ${{steps.export.outputs.vpc_id}}
        ecs_repo_name: ${{steps.export.outputs.ecs_repo_name}}
        aws_account_id: ${{steps.export.outputs.aws_account_id}}

  deploy:
    runs-on: ubuntu-latest
    needs: terraform
    steps:

      - name: Output Common variables
        run: |
          echo "aws_account_id=${{ needs.terraform.outputs.aws_account_id }}" >> $GITHUB_ENV
          echo "ecs_repo_name=${{ needs.terraform.outputs.ecs_repo_name }}" >> $GITHUB_ENV
          echo "ECR_REPO_URI=${{ needs.terraform.outputs.aws_account_id }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ needs.terraform.outputs.ecs_repo_name }}" >> $GITHUB_ENV 
          echo "aws_region=${{ secrets.AWS_REGION }}" >> $GITHUB_ENV
          echo "vpc_id=${{ needs.terraform.outputs.vpc_id }}" >> $GITHUB_ENV

      - name: Print common variables 
        run: |
          echo "Using ECR URI: $ECR_REPO_URI"
          echo "vpc_id: $vpc_id"
          echo "aws_account_id: ${{ needs.terraform.outputs.aws_account_id }}"
          echo "ecs_repo_name: $ecs_repo_name"

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin $ECR_REPO_URI 

      - name: Build and Push Docker Image
        run: |
          docker build -t myapp ./app/
          docker tag myapp:latest  $ECR_REPO_URI:myapp
          docker push  $ECR_REPO_URI:myapp
